# Generated by Django 4.2.6 on 2023-11-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_options_libro_imagen_alter_libro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='', upload_to='libros', verbose_name='imagen'),
        ),
    ]
