# Generated by Django 4.2.6 on 2023-11-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='númeroDeInventario',
            field=models.IntegerField(default=0, verbose_name='Número de Inventario'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='ISBN',
            field=models.CharField(max_length=150, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=200, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='', upload_to='libros', verbose_name='Imágen'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
    ]
