# Generated by Django 4.2.6 on 2023-11-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_libro_númerodeinventario_alter_libro_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='', max_length=300, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.CharField(default='', max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Disponibilidad'),
        ),
    ]
