# Generated by Django 4.2.6 on 2023-11-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_libro_descripcion_libro_genero_alter_libro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.CharField(default='', max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(choices=[('Aventura', 'Aventura'), ('Ciencia Ficción', 'Ciencia Ficción'), ('Drama', 'Drama'), ('Fantasía', 'Fantasía'), ('Misterio', 'Misterio')], default='', max_length=100, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(default='', upload_to='libros', verbose_name='Imagen'),
        ),
    ]
