# Generated by Django 4.2.6 on 2023-11-20 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_alter_libro_descripcion_alter_libro_genero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='númeroDeInventario',
            new_name='numDeInventario',
        ),
    ]
