# Generated by Django 4.2.6 on 2023-11-28 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0007_rename_númerodeinventario_libro_numdeinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nota', models.CharField(max_length=150, verbose_name='Nota')),
                ('libroAlquilado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'registro',
                'verbose_name_plural': 'registros',
                'ordering': ['-created'],
            },
        ),
    ]
